/**
 * 中文
 */

module.exports = {
    'Assignee':'代理人',
    'Candidate Groups':'候选组',
    'Candidate Users':'候选人',
    'Due Date':'到期日',
    'Follow Up Date':'跟踪日期',
    'Priority':'优先',
    'General':'一般信息',
    'Listeners':'监听',
    'Extensions':'扩展',
    'Name':'名称',
    'Version Tag':'版本标签',
    'Executable':'可执行文件',
    'External Task Configuration':'外部任务配置',
    'Task Priority':'任务优先级',
    'Job Configuration':'作业配置',
    'Job Priority':'工作优先级',
    'Documentation':'文档',
    'Element Documentation':'元素文献',
    'History Configuration':'历史配置',
    'History Time To Live':'历史生存时间',
    'Details':'详情',
    'Initiator':'发起者',
    'Asynchronous Continuations':'异步连续',
    'Asynchronous Before':'异步之前',
    'Asynchronous After':'异步之后',
    'Forms':'表单',
    'Input/Output':'输入/输出',
    'Properties':'属性',
    'Add Property':'添加属性',
    'value':'值',
    'Parameters':'参数',
    'Input Parameters':'输入参数',
    'Output Parameters':'输出参数',
    'Execution Listener':'执行监听',
    'Task Listener':'任务监听',
};
